# Generated by Django 5.0.2 on 2024-02-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('generic_name', models.CharField(max_length=300)),
                ('mg_dose', models.CharField(max_length=200)),
                ('exipiry_date', models.DateField()),
                ('manufacture_date', models.DateField()),
            ],
        ),
    ]
