# Generated by Django 5.0.2 on 2024-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
