# Generated by Django 5.0.2 on 2024-03-04 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='medicine',
        ),
        migrations.AddField(
            model_name='medicine',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_location', to='system.location'),
        ),
    ]
